Feature/stores
Caps-Looking/Dealership pull request #1
Opened 2022-08-03 15:25 UTC by Caps-Looking

2022-08-03 16:26 UTC, joaomangilli requested changes

2022-08-03 16:26 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +  class StoresController < ApplicationController
Algo que vc pode fazer é um before action, tipo assim:

```ruby
before_action :set_store, only: [:show, :edit, :update, :destroy]
```

Ai vc nao precisa chamar dentro das actions.

2022-08-03 16:26 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +      params.require(:store).permit(
Não precisa do to_h e como os parametros sao os mesmos na atualizacao e criacao vc pode usar o mesmo metodo

2022-08-03 16:26 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +      redirect_to admin_stores_path, status: :see_other
see_other?

2022-08-03 16:26 UTC, joaomangilli commented on app/models/store.rb
> +  validates :cep, :country, :state, :city,
A ideia é que o endereço fique numa entidade ou tabela separada

2022-08-03 16:26 UTC, joaomangilli commented on app/views/admin/stores/new.html.erb
> +<%= simple_form_for @store, method: :post, url: admin_stores_path do |f| %>
Como o edit e o new tem os mesmos inputs, vc pode reutilizar a view, se nao souber como fazer isso e nao encontrar pode me chamar

2022-08-03 16:26 UTC, joaomangilli commented on app/views/admin/stores/edit.html.erb
> +<h1>Edit Store</h1>
A gente nao coloca string fixa no html, sempre usamos i18n. Se nao souber como fazer ou nao encontrar me pergunta

2022-08-03 16:26 UTC, joaomangilli commented on db/migrate/20220802184547_create_stores.rb
> +      t.string :name, limit: 50
É necessario adicionar tambem null: false para os campos que sao obrigatorios

2022-08-03 16:26 UTC, joaomangilli commented on spec/features/store/editing_store_spec.rb
> +      expect(page).to have_text("can't be blank")
```suggestion
      expect(page).to have_text('can't be blank')
```

2022-08-03 16:26 UTC, joaomangilli commented on spec/features/store/showing_store_spec.rb
> +describe 'Store Showing' do
Como é um projeto de testes nao tem problema, mas para vc saber geralmente a gente colocaria tudo dentro de um store_spec pq esses testes sao lentos pra carregar e se vc coloca em arquivos separados é necessario fazer reload pra cada arquivo

2022-08-03 16:26 UTC, joaomangilli commented on db/migrate/20220802184547_create_stores.rb
> +      t.string :country
Nao precisa do country

2022-08-03 16:26 UTC, joaomangilli commented on db/migrate/20220802184547_create_stores.rb
> +      t.string :cep
Vamos limitar os campos do endereço a 50 caracteres, com exceção da street que pode ter 100 e do complemento que pode ter 1000

2022-08-03 16:26 UTC, joaomangilli commented on app/views/admin/stores/new.html.erb
> +    <%= f.input :cep, input_html: { autocomplete: "off" } %>
O cep deve ter mascara

2022-08-03 16:26 UTC, joaomangilli commented on app/models/store.rb
> +  validates :name, uniqueness: true, presence: true
É necessario validar o tamanho dos campos

2022-08-03 16:26 UTC, joaomangilli commented on app/models/store.rb
> +  validates :cep, :country, :state, :city,
Number pode ser uma string no banco, mas acho que aqui devemos validar como numero, ou tem algum tipo de endereco no brasil que nao usa integer para numero?

2022-08-03 16:30 UTC, Caps-Looking commented on spec/features/store/editing_store_spec.rb
> +      expect(page).to have_text("can't be blank")
aqui não tem como porque tá usando aspas imples pro `can't`

2022-08-03 21:51 UTC, joaomangilli commented on app/models/address.rb
> +  validates :number, format: { with: /[0-9]/ }
https://edgeguides.rubyonrails.org/active_record_validations.html#numericality

2022-08-03 21:51 UTC, joaomangilli commented on app/models/store.rb
> +  validates :name, uniqueness: true, presence: true
Precisa validar o tamanho do campo

2022-08-03 21:51 UTC, joaomangilli commented on app/views/admin/stores/_form.html.erb
> +    <%= f.submit "Save" %>
i18n

2022-08-03 21:51 UTC, joaomangilli commented on app/views/admin/stores/_form.html.erb
> +    <%= f.simple_fields_for :address do |a| %>
Eu acho que dava pra extrair numa view separada que pode ficar dentro de uma pasta address, assim pode ser reutilizavel

2022-08-03 21:51 UTC, joaomangilli commented on app/views/admin/stores/show.html.erb
> +<b>CEP:</b> <%= @store.address.cep %> </br>
I18n

2022-08-03 21:51 UTC, joaomangilli commented on app/views/layouts/application.html.erb
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
https://github.com/rails/jquery-rails

2022-08-03 21:51 UTC, joaomangilli commented on db/migrate/20220802184547_create_stores.rb
> +class CreateStores < ActiveRecord::Migration[7.0]
Aqui vc pode deixar desse jeito pq eh apenas um projeto teste, mas em projetos reais a gente geralmente deleta migrations que deram errado e deixa tudo dentro de um arquivo, pra evitar crescer muito. Aqui no caso teriamos 2. Um para address e outro para store

2022-08-03 21:51 UTC, joaomangilli commented on db/migrate/20220803190759_add_address_to_stores.rb
> +      t.belongs_to :address
Esse cara deve ser not null

2022-08-03 21:51 UTC, joaomangilli commented on spec/features/store/editing_store_spec.rb
> +      expect(page).to have_text("can't be blank")
```suggestion
      expect(page).to have_text('can't be blank')
```

2022-08-03 21:51 UTC, joaomangilli commented on spec/models/store_spec.rb
> +    it { is_expected.to validate_uniqueness_of :name }
Deve validar a presença do endereco tambem

2022-08-03 21:51 UTC, joaomangilli commented on app/models/address.rb
> +  validates :cep, :state, :city, :district, :number,
Number pode ter apenas 1 de tamanho

2022-08-03 21:51 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +    def create
Se eu tentar salvar um nome muito grande ou estender o tamanho em qualquer outro campo, nada acontece e o registro nao é salvo

2022-08-03 21:51 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +    def destroy
Por algum motivo quando faz o destroy tah retornando para show e dando erro

2022-08-03 21:51 UTC, joaomangilli commented on app/controllers/admin/stores_controller.rb
> +    def show; end
Nao precisa nem do show nem do edit

2022-08-03 21:51 UTC, joaomangilli commented on config/locales/en.yml
> +  new_store: "New Store"
Todas essas chaves vao ficar dentro de uma chave `store`. Ai vc pode usar apenas new, edit, etc.

Alem disso é preciso traduzir os campos do model para o simple form usar

2022-08-03 21:51 UTC, joaomangilli commented on app/models/address.rb
> +  has_one :store, dependent: :destroy
Nao necessariamente a gente vai destruir uma loja quando destruir um endereço, isso pode causar bugs na app, acho que deve deixar quebrar

2022-08-04 17:03 UTC, joaomangilli commented on app/models/address.rb
> +  has_one :store, dependent: :nullify
aqui nao vai conseguir nulificar pq address eh obrigatorio na store, na verdade tem q deixar quebrar mesmo pq teoricamente nao deveria se apagar um endereco associado a uma store, entao acho q da pra remover essa linha

2022-08-04 17:03 UTC, joaomangilli commented on app/views/admin/addresses/_form.html.erb
> +    <%= a.input :cep, label: t('address.cep'), input_html: { autocomplete: "off", onkeypress: "$(this).mask('00000-000')" }%>
Nao precisa passar o label aqui, vc pode definir tudo dentro do i18n https://github.com/heartcombo/simple_form#i18n

2022-08-04 17:03 UTC, joaomangilli commented on app/views/admin/stores/_form.html.erb
> +    <%= f.submit t('general.save') %>
aqui tambem nao precisa passar o i18n ate onde lembro

2022-08-04 17:03 UTC, joaomangilli commented on app/views/admin/stores/_form.html.erb
> +    <%= render 'admin/addresses/form', f: %>
nao precisa passar `f: f `?

2022-08-04 17:03 UTC, joaomangilli commented on config/locales/en.yml
>  en:
Tenta seguir essa padrao de organizaçao https://guides.rubyonrails.org/i18n.html#organization-of-locale-files

Geralmente os projetos estao dessa forma

2022-08-04 17:03 UTC, joaomangilli commented on config/locales/pt-BR.yml
> +      required: "precisa existir"
Vc pode usar essa gem ao inves de fazer na mao: https://github.com/svenfuchs/rails-i18n

2022-08-04 17:03 UTC, joaomangilli commented on config/locales/simple_form.en.yml
> +en:
Eu acho que vai precisar desse em portugues tambem neh?

2022-08-04 17:05 UTC, Caps-Looking commented on app/views/admin/stores/_form.html.erb
> +    <%= render 'admin/addresses/form', f: %>
quando a variável é a mesma que o atributo, dá pra passar assim

2022-08-04 19:34 UTC, joaomangilli commented on app/views/admin/stores/show.html.erb
> +<b><%= t('activerecord.attributes.address.cep') %>:</b> <%= @store.address.cep %> </br>
aqui vc pode usar o delegate. tipo la no model de store vc pode colocar algo como: `delegate :cep, :state, etc, to: :address`, ai vc pode acessar `@store.cep`. Vc pode usar delegate para qualquer classe, nao apenas nos models

2022-08-04 19:34 UTC, joaomangilli commented on app/views/admin/stores/show.html.erb
> +<b><%= t('activerecord.attributes.address.cep') %>:</b> <%= @store.address.cep %> </br>
https://apidock.com/rails/Module/delegate

2022-08-04 19:34 UTC, joaomangilli commented on config/locales/defaults/en.yml
> +en:
De acordo com https://guides.rubyonrails.org/i18n.html#organization-of-locale-files nos temos um padrao para as views tambem. No caso essas informacoes aqui ficariam dentro de uma pasta views, ai o general ficaria dentro de default e o store dentro de store.

2022-08-04 19:34 UTC, joaomangilli commented on config/locales/models/address/pt-BR.yml
> +pt-BR:
Faltou os models em ingles

2022-08-04 19:34 UTC, joaomangilli commented on app/models/address.rb
> +  validates :cep, :state, :city, :district, presence: true, length: { in: 2..50 }
O CEP deve ter o tamanho especifico de 8 char, senhao a gente pode colocar tipo 5 digitos e deve ser sempre 8

2022-08-04 19:34 UTC, joaomangilli commented on config/locales/defaults/en.yml
> +en:
Ah e no caso das views elas sempre ficam dentro de uma key views:

```
en:
  views:
    ....
```

2022-08-04 19:47 UTC, Caps-Looking commented on app/models/address.rb
> +  validates :cep, :state, :city, :district, presence: true, length: { in: 2..50 }
vou colocar 9 pra contar com o `-` da máscara

2022-08-05 14:46 UTC, joaomangilli commented on app/models/address.rb
> +  validates :cep, :state, :city, :district, presence: true, length: { in: 2..50 }
Tem que remover o cep daqui

2022-08-05 14:46 UTC, joaomangilli commented on app/models/address.rb
> +  validates :cep, presence: true, length: { minimum: 9, maximum: 9 }
```suggestion
  validates :cep, presence: true, length: { is: 9 }
```

2022-08-05 14:46 UTC, joaomangilli commented on app/views/admin/stores/show.html.erb
> +<b><%= t('activerecord.attributes.address.cep') %>:</b> <%= @store.address.cep %> </br>
```suggestion
<b><%= t('activerecord.attributes.address.cep') %>:</b> <%= @store.cep %> </br>
```

2022-08-05 14:46 UTC, joaomangilli commented on config/locales/defaults/en.yml
> +  store:
Pq esse ficou aqui?

2022-08-05 14:46 UTC, joaomangilli commented on config/locales/models/store/en.yml
> +    models:
Eu acho que aqui deveria ser store, certo?

2022-08-05 14:58 UTC, joaomangilli approved these changes

2022-08-05 15:03 UTC, merged